# Generated by Django 4.1 on 2022-08-21 12:28

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='Anonymous', max_length=40, verbose_name='Name')),
                ('body', models.CharField(db_index=True, default="What's Happenning?", max_length=140, verbose_name='Body')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Post Image')),
                ('like_count', models.PositiveIntegerField(blank=True, default=0, verbose_name='Likes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Post Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Post Updated At')),
            ],
            options={
                'db_table': 'Post',
            },
        ),
    ]
